CHAT_AUTOR_HUMANO = 1
CHAT_AUTOR_IA = 2

CHOICES_CHAT_AUTOR = (
    (CHAT_AUTOR_HUMANO, 'Humano'),
    (CHAT_AUTOR_IA, 'IA')
)

TRANSCRICAO_TIPO_VIDEO = 1
TRANSCRICAO_TIPO_AUDIO = 2

CHOICES_TRANSCRICAO_TIPO = (
    (TRANSCRICAO_TIPO_VIDEO, 'Vídeo'),
    (TRANSCRICAO_TIPO_AUDIO, 'Audio')
)

STATUS_FILA_PROCESSAMENTO = 1
STATUS_PROCESSANDO_ARQUIVO = 2
STATUS_FAZENDO_TRANSCRICAO = 3
STATUS_CONCLUIDO = 4
STATUS_CANCCELADO = 5
STATUS_FALHA_PROCESSAMENTO = 6
STATUS_FALHA_TRANSCRICAO = 7


CHOICES_STATUS_TRANSCRICAO = (
    (STATUS_FILA_PROCESSAMENTO, 'Na fila de processamento'),
    (STATUS_PROCESSANDO_ARQUIVO, 'Processando o arquivo'),
    (STATUS_FAZENDO_TRANSCRICAO, 'Fazendo a transcrição'),
    (STATUS_CONCLUIDO, 'Concluído'),
    (STATUS_CANCCELADO, 'Cancelado'),
    (STATUS_FALHA_PROCESSAMENTO, 'Falha no processamento do arquivo'),
    (STATUS_FALHA_TRANSCRICAO, 'Falha na transcrição'),
)

STATUS_OCR_FILA = 1
STATUS_OCR_PROCESSANDO = 2
STATUS_PDF_ENVIANDO_ARQUIVO = 3
STATUS_OCR_CONCLUIDO = 4
STATUS_OCR_CANCELADO = 5
STATUS_OCR_FALHA_PROCESSAMENTO = 6
STATUS_PDF_FALHA_ENVIO = 7
STATUS_OCR_DISPENSADO = 8


CHOICES_STATUS_PDF = (
    (STATUS_OCR_FILA, 'Na fila de processamento'),
    (STATUS_OCR_PROCESSANDO, 'Processando o arquivo'),
    (STATUS_PDF_ENVIANDO_ARQUIVO, 'Enviando arquivo para IA'),
    (STATUS_OCR_CONCLUIDO, 'Concluído'),
    (STATUS_OCR_CANCELADO, 'Cancelado'),
    (STATUS_OCR_FALHA_PROCESSAMENTO, 'Falha no processamento do arquivo'),
    (STATUS_PDF_FALHA_ENVIO, 'Falha no envio do arquivo para IA'),
    (STATUS_OCR_DISPENSADO, 'Processamento dispensado'),
)