CHAT_AUTOR_HUMANO = 1
CHAT_AUTOR_IA = 2

CHOICES_CHAT_AUTOR = (
    (CHAT_AUTOR_HUMANO, 'Humano'),
    (CHAT_AUTOR_IA, 'IA')
)

TRANSCRICAO_TIPO_VIDEO = 1
TRANSCRICAO_TIPO_AUDIO = 2

CHOICES_TRANSCRICAO_TIPO = (
    (TRANSCRICAO_TIPO_VIDEO, 'Vídeo'),
    (TRANSCRICAO_TIPO_AUDIO, 'Audio')
)