# Generated by Django 3.2.7 on 2024-04-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('documento', models.FileField(upload_to='documento_chat', verbose_name='Documento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('chatpdf_source_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chat PDF source id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaTranscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo')),
                ('arquivo', models.FileField(upload_to='arquivo_transcricao', verbose_name='Arquivo')),
                ('legenda', models.FileField(blank=True, null=True, upload_to='legenda_transcricao', verbose_name='Legenda')),
                ('tipo', models.IntegerField(choices=[(1, 'Vídeo'), (2, 'Audio')], verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('diarizacao', models.TextField(blank=True, null=True, verbose_name='Diarização')),
                ('transcricao', models.TextField(blank=True, null=True, verbose_name='Transcrição')),
                ('status', models.IntegerField(choices=[(1, 'Na fila de processamento'), (2, 'Processando o arquivo'), (3, 'Fazendo a transcrição'), (4, 'Concluido'), (5, 'Cancelado'), (6, 'Falha no processamento do arquivo'), (7, 'Falha na transcrição')], default=1, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('texto', models.TextField(verbose_name='mensagem')),
                ('autor', models.IntegerField(choices=[(1, 'Humano'), (2, 'IA')], verbose_name='Autor')),
                ('is_favorito', models.BooleanField(default=False, verbose_name='Favorito por usuário')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Transcricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('texto', models.TextField(verbose_name='Texto')),
                ('tempo_inicial', models.CharField(max_length=12, verbose_name='Tempo inicial')),
                ('tempo_inicial_segundos', models.IntegerField(default=0, verbose_name='Tempo inicial em segundos')),
                ('tempo_final', models.CharField(max_length=12, verbose_name='Tempo final')),
                ('speaker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Speaker')),
                ('cor_speaker', models.CharField(default='#0000FF', max_length=50, verbose_name='Cor do Speaker')),
                ('is_favorito', models.BooleanField(default=False, verbose_name='Favorito por usuário')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
