# Generated by Django 3.2.7 on 2024-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatranscricao',
            name='visualizado',
            field=models.BooleanField(default=False, verbose_name='Visualizado'),
        ),
    ]
