# Generated by Django 3.2.7 on 2024-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_mediatranscricao_visualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='md5_hexdigit',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mediatranscricao',
            name='md5_hexdigit',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
