# Generated by Django 3.2.7 on 2024-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_assistentemensagem_assistenteperfil_assistentetopico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='md5_hexdigit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mediatranscricao',
            name='md5_hexdigit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
