# Generated by Django 3.2.7 on 2024-05-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_auto_20240424_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcricao',
            name='is_vetado',
            field=models.BooleanField(default=False, verbose_name='Vetado pelo usuário'),
        ),
    ]
