# Generated by Django 3.2.7 on 2024-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_alter_assistentetopico_openia_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistentetopico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
