# Generated by Django 3.2.7 on 2024-06-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0007_transcricao_is_vetado'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistenteperfil',
            name='grupo_permissao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Permissão'),
        ),
    ]
