# Generated by Django 3.2.7 on 2024-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0008_assistenteperfil_grupo_permissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.IntegerField(choices=[(1, 'Na fila de processamento'), (2, 'Processando o arquivo'), (3, 'Enviando arquivo para IA'), (4, 'Concluido'), (5, 'Cancelado'), (6, 'Falha no processamento do arquivo'), (7, 'Falha no envio do arquivo para IA'), (8, 'Processamento dispensado')], default=8, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='chat',
            name='visualizado',
            field=models.BooleanField(default=False, verbose_name='Visualizado'),
        ),
    ]
