# Generated by Django 3.2.7 on 2024-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0009_auto_20240625_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='log_errors',
            field=models.TextField(blank=True, null=True, verbose_name='Log errors'),
        ),
    ]
