# Generated by Django 3.2.7 on 2024-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0010_chat_log_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_martinha_processando',
            field=models.BooleanField(blank=True, null=True, verbose_name='Processado pela Martinha'),
        ),
        migrations.AddField(
            model_name='mediatranscricao',
            name='is_tanaka_processando',
            field=models.BooleanField(blank=True, null=True, verbose_name='Processado pelo tanaka'),
        ),
    ]
