# Generated by Django 3.2.7 on 2024-09-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0011_auto_20240826_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatranscricao',
            name='duracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documento_chat', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.IntegerField(choices=[(1, 'Na fila de processamento'), (2, 'Processando o arquivo'), (3, 'Enviando arquivo para IA'), (4, 'Concluído'), (5, 'Cancelado'), (6, 'Falha no processamento do arquivo'), (7, 'Falha no envio do arquivo para IA'), (8, 'Processamento dispensado')], default=8, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mediatranscricao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivo_transcricao', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='mediatranscricao',
            name='status',
            field=models.IntegerField(choices=[(1, 'Na fila de processamento'), (2, 'Processando o arquivo'), (3, 'Fazendo a transcrição'), (4, 'Concluído'), (5, 'Cancelado'), (6, 'Falha no processamento do arquivo'), (7, 'Falha na transcrição')], default=1, verbose_name='Status'),
        ),
    ]
