# Generated by Django 3.2.7 on 2024-04-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='Não obtido', max_length=300)),
                ('ip', models.CharField(blank=True, default='Não obtido', max_length=20)),
                ('ip_publico', models.CharField(blank=True, default='Não obtido', max_length=20)),
                ('navegador', models.CharField(blank=True, default='Não obtido', max_length=300)),
                ('url', models.CharField(blank=True, default='Não obtido', max_length=300)),
                ('url_atual', models.CharField(blank=True, default='Não obtido', max_length=500)),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('metodo', models.CharField(blank=True, default='Não obtido', max_length=10)),
                ('parametros', models.TextField(blank=True, default='Não obtido')),
                ('response', models.TextField(blank=True, default='Não obtido')),
            ],
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=500, verbose_name='url')),
            ],
            options={
                'verbose_name': 'usuário página',
                'verbose_name_plural': 'Usuários página',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'usuário online',
                'verbose_name_plural': 'Usuários online',
            },
        ),
    ]
