# Generated by Django 3.2.7 on 2024-04-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrib', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nacionalidades',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nacionalidades_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nacionalidades',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nacionalidades_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='municipios',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipios_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='municipios',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipios_estado', to='contrib.estados'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipios_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='municipios',
            name='municipios_responsaveis',
            field=models.ManyToManyField(blank=True, help_text='\n                                                        Selecione os municipios que serão responsáveis pelos \n                                                        atendimentos deste municipio, caso ele não possua unidade da defensoria', related_name='municipios_municipios_responsaveis', to='contrib.Municipios', verbose_name='Municipio(s) responsável(is)'),
        ),
        migrations.AddField(
            model_name='estadoscivis',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoscivis_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadoscivis',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoscivis_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estados',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estados_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estados',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estados_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escolaridades',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolaridades_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escolaridades',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolaridades_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assinaturadocumento_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assinaturadocumento_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
