# Generated by Django 3.2.7 on 2024-04-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lembretes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('url_solicitada', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Pendente'), (2, 'Visualizado'), (3, 'Cancelado'), (4, 'Finalizado')], null=True, verbose_name='Status')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Media'), (3, 'Alta')], default=1, verbose_name='Prioridade')),
                ('lembrete_proprio', models.BooleanField(default=False, verbose_name='Lembrete próprio')),
                ('documento', models.FileField(blank=True, null=True, upload_to='lembretes')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
            },
        ),
    ]
