# Generated by Django 3.2.7 on 2024-04-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lembrete', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lembretes',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lembretes_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lembretes',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lembretes_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='lembretes',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lembretes_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
