# Generated by Django 3.2.7 on 2024-04-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrib', '0001_initial'),
        ('certidao_localizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certidao',
            name='assinatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contrib.assinaturadocumento', verbose_name='Assinatura Documento'),
        ),
    ]
